name: Check Package

on:
  push:
    branches: [main, conventional-commits-and-auto-releases]
  pull_request:
    branches: '*'
  workflow_dispatch:
  

jobs:
  test-package:
    name: Lint, Test and Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [18.x, 20.x, 'lts/*']
        os: [ubuntu-latest]
    steps:
      - name: Cloning GitHub Repository
        uses: actions/checkout@v3

      - name: Setting up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run build
