name: Test (and publish if on main)

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  quality-check:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        container: 
          - node:18-bullseye
          - node:20-bullseye
          - node:22-bullseye
          - node:lts-bullseye
    container: ${{ matrix.container }}
    steps:
      - name: Cloning GitHub Repository
        uses: actions/checkout@v3

      - name: Install system dependencies for Playwright
        run: |
          apt-get update
          apt-get install -y wget gnupg ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libxcomposite1 libxdamage1 libxrandr2 xdg-utils libxshmfence1 libxss1 libxtst6 libu2f-udev

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run build

  publish:
    name: Publish on main
    runs-on: ubuntu-latest
    container: node:lts-bullseye
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality-check]
    steps:
      - name: Cloning GitHub Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Configure Git for HTTPS and GH_TOKEN
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://$GH_TOKEN@github.com/${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}

      - name: Debug Git Remote Info
        run: |
          echo "Git remote URL:"
          git remote -v
          echo "Git config:"
          git config --list --show-origin

      - name: Release
        run: npx semantic-release --debug
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
